chore: changed dataset endpoints to use RTK
yourtrading-ai/Fishnet pull request #19
Opened 2024-06-26 07:51 UTC by manomage

2024-06-26 11:20 UTC, MHHukiewitz requested changes
Stopped reviewing after the first four files. There is a couple of issues that need to be addressed, before this can be actually reviewed:
- Handle Windows-style CRLF `\r\n\` vs Unix new line `\n` file formatting. See https://www.edwardthomson.com/blog/git_for_windows_line_endings.html for further guidance.
- Including reformatted files in a PR that does not touch any of their functionality, WITHOUT the PR being a pure formatting PR is highly discouraged, especially as this PR fixes bugs/changes functionality and has blown up to +2,782 −2,710 line changes.

The above make the diff so large, that it is very difficult for a reviewer to spot actual changes and to understand their impact on the functionality of the code.

Please split the formatting of the untouched files into another PR, while keeping only the relevant files for functional changes in this PR.

2024-06-26 11:20 UTC, MHHukiewitz commented on src/features/auth/hook.ts
This looks like exactly the same file. Did you maybe change the line break symbols? Please check if this might be the case here: https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

2024-06-26 11:20 UTC, MHHukiewitz commented on src/features/data/components/BrowseDataTable.tsx
Please only include formatting changes on files that you actually changed in a PR, that includes new/changed features.

If you reformat unrelated project files, please do so in a seperate formatting PR.

2024-06-26 11:20 UTC, MHHukiewitz commented on src/features/data/components/DataChart.tsx
Same problem here, there are no actual changes in this file

2024-06-26 11:20 UTC, MHHukiewitz commented on src/features/data/components/DownloadButton.tsx
Wasn't this file added in #18?

2024-06-26 13:31 UTC, manomage commented on src/features/data/components/BrowseDataTable.tsx
The file was relocated to the features folder. 

The `IDataset ` is now imported from the new data types file

2024-06-26 13:33 UTC, manomage commented on src/features/data/components/DataChart.tsx
Moved `DataChart.tsx` from pages to features.

2024-06-26 13:37 UTC, manomage commented on src/features/data/components/DownloadButton.tsx
This particular file was moved under the data folder in the features folder.

2024-06-26 13:49 UTC, manomage commented on src/features/auth/hook.ts
That's not really the case. I used ESLINT to format the files when I was resolving the conflict from the main branch.

2024-06-26 13:55 UTC, manomage commented
> Stopped reviewing after the first four files. There is a couple of issues that need to be addressed, before this can be actually reviewed:
> 
> * Handle Windows-style CRLF `\r\n\` vs Unix new line `\n` file formatting. See https://www.edwardthomson.com/blog/git_for_windows_line_endings.html for further guidance.
> * Including reformatted files in a PR that does not touch any of their functionality, WITHOUT the PR being a pure formatting PR is highly discouraged, especially as this PR fixes bugs/changes functionality and has blown up to +2,782 −2,710 line changes.
> 
> The above make the diff so large, that it is very difficult for a reviewer to spot actual changes and to understand their impact on the functionality of the code.
> 
> Please split the formatting of the untouched files into another PR, while keeping only the relevant files for functional changes in this PR.

Currently I'm making all the endpoints on the codebase to use RTK Query and also refactoring and optimising the codebase that's why some files are being moved to another folder.

2024-06-26 14:57 UTC, MHHukiewitz commented on src/features/auth/hook.ts
Why is this file then seemingly having a diff, when there is none? ESLINT does not take care of this phenomenom AFAIK

2024-06-26 15:56 UTC, MHHukiewitz commented on src/pages/my-profile/components/Overview.tsx
This file looks also as if it did not change at all, why?

2024-06-29 21:18 UTC, MHHukiewitz commented
Closed in favor of #21

2024-06-29 21:18 UTC, closed without merging